services:
  mongo:
    image: mongo:7.0
    container_name: ecommerce_receipts_mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - receipt_network

  redis:
    image: redis:7.2-alpine
    container_name: ecommerce_receipts_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - receipt_network

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: ecommerce_receipts_rabbitmq
    restart: always
    ports:
      - "5672:5672"     # AMQP Protocol
      - "15672:15672"   # Management Web UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - receipt_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce_receipts_api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=ecommerce_receipts
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - REDIS_URL=redis://redis:6379/0
      - USE_REDIS_CACHE=true
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - USE_RABBITMQ=true
    depends_on:
      - mongo
      - redis
      - rabbitmq
    networks:
      - receipt_network

networks:
  receipt_network:
    driver: bridge

volumes:
  mongo_data:
  redis_data:
  rabbitmq_data:
